create table if not exists documents (
                                         id bigint generated by default as identity primary key,
                                         title varchar(255),
                                         source varchar(255),
                                         created_at timestamp default current_timestamp
);

create table if not exists chunks (
                                      id bigint generated by default as identity primary key,
                                      document_id bigint not null,
                                      chunk_index int not null,
                                      content text not null,
                                      embedding vector(768),
                                      created_at timestamp default current_timestamp,
                                      constraint fk_chunks_document foreign key (document_id) references documents(id)
);